---
- hosts: all
  tasks:
   - name: Ensure Nginx is installed at 1.12
     shell: sudo amazon-linux-extras install nginx1.12
   - name: start nginx
     service:
       name: nginx
       state: started
