---
#bootstrap.yml will install Python
- import_playbook: bootstrap.yml

- hosts: all
  tasks:
   - name: Ensure Latest Nginx is installed
     yum:
        name: nginx
        state: latest

   - name: start nginx
     service:
        name: nginx
        state: started
