---
- import_playbook: bootstrap.yml

- hosts: all
  tasks:
   - name: Ensure Nginx is installed at 1.12
     yum:
        name: nginx
        state: latest

   - name: start nginx
     service:
        name: nginx
        state: started
